-- Create users table
create table if not exists public.users (
  wallet_address text primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create user_nfts table (ownership)
create table if not exists public.user_nfts (
  id bigint generated by default as identity primary key,
  user_wallet text references public.users(wallet_address) not null,
  nft_id bigint references public.nfts(id) not null,
  purchased_at timestamp with time zone default timezone('utc'::text, now()) not null,
  transaction_hash text
);

-- Create donations table (impact)
create table if not exists public.donations (
  id bigint generated by default as identity primary key,
  user_wallet text references public.users(wallet_address) not null,
  amount_eth numeric not null,
  station_id text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.users enable row level security;
alter table public.user_nfts enable row level security;
alter table public.donations enable row level security;

-- Policies
create policy "Users can read their own data" on public.users
  for select using (auth.uid()::text = wallet_address or true); -- Simplified for demo, ideally use auth.uid() if using Supabase Auth, but here we use wallet address as ID. 
  -- Since we are not using Supabase Auth fully yet (just public client), we'll allow public read for now or restrict by wallet in query.
  -- For this demo with just public client, we will allow public read to simplify fetching by wallet address.
create policy "Public read users" on public.users for select using (true);

create policy "Public read user_nfts" on public.user_nfts for select using (true);
create policy "Public read donations" on public.donations for select using (true);

-- Insert sample data for testing
-- NOTE: Replace '0x123...' with your actual wallet address to see data immediately
insert into public.users (wallet_address) values ('0x1234567890abcdef1234567890abcdef12345678') on conflict do nothing;

-- Assign some NFTs to this user
insert into public.user_nfts (user_wallet, nft_id, transaction_hash) 
select '0x1234567890abcdef1234567890abcdef12345678', id, '0xhash1'
from public.nfts
limit 3;

-- Add some donations
insert into public.donations (user_wallet, amount_eth, station_id)
values 
('0x1234567890abcdef1234567890abcdef12345678', 0.05, 'lima'),
('0x1234567890abcdef1234567890abcdef12345678', 0.02, 'norte');
