-- Create the table for NFTs
create table if not exists public.nfts (
  id bigint generated by default as identity primary key,
  name text not null,
  image_url text not null,
  price numeric not null,
  rarity text not null,
  fire_station text not null,
  region text not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.nfts enable row level security;

-- Create a policy that allows anyone to read the NFTs
create policy "Enable read access for all users"
on public.nfts
for select
using (true);

-- Insert sample data (matching the previous MOCK_NFTS)
insert into public.nfts (name, price, image_url, fire_station, region, rarity, description)
values
  ('Bombero Elite #001', 0.05, '/hero-firefighter.png', 'B-4 Lima', 'lima', 'Legendary', 'Un héroe legendario de la estación B-4 Lima.'),
  ('Rescate Urbano #042', 0.02, '/hero-firefighter.png', 'B-10 Salvadora Lima', 'lima', 'Rare', 'Especialista en rescate urbano.'),
  ('Unidad Hazmat #103', 0.03, '/hero-firefighter.png', 'B-4 Lima', 'lima', 'Epic', 'Experto en materiales peligrosos.'),
  ('Voluntario #88', 0.01, '/hero-firefighter.png', 'B-4 Lima', 'lima', 'Common', 'Voluntario dedicado al servicio.'),
  ('Jefe de Brigada', 0.10, '/hero-firefighter.png', 'B-10 Salvadora Lima', 'lima', 'Legendary', 'Líder experimentado de la brigada.'),
  ('Operador de Bomba', 0.02, '/hero-firefighter.png', 'B-27 Salvadora Chiclayo', 'norte', 'Rare', 'Operador de maquinaria pesada.'),
  ('Paramédico #12', 0.04, '/hero-firefighter.png', 'B-27 Salvadora Chiclayo', 'norte', 'Epic', 'Salva vidas en situaciones críticas.'),
  ('Cadete #05', 0.005, '/hero-firefighter.png', 'B-19 Arequipa', 'sierra-sur', 'Common', 'Futuro héroe en entrenamiento.'),
  ('Rescate Andino #01', 0.06, '/hero-firefighter.png', 'B-56 Huancayo', 'sierra-centro', 'Epic', 'Especialista en rescate de alta montaña.'),
  ('Guardián Amazónico', 0.05, '/hero-firefighter.png', 'B-72 Iquitos', 'selva', 'Legendary', 'Protector de la selva amazónica.');
